plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/npm'
  - '@semantic-release/github'
  - - '@semantic-release/git'
    - assets:
        - 'build/*.wat'
        - 'assembly/__tests__/**/*.{wat,wasm,map}'
        - 'package.json'
      message: |-
        chore(release): ${nextRelease.version} [skip ci]

        ${nextRelease.notes}
